# Generated by Django 3.1.2 on 2020-10-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201001_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviemodel',
            options={'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільми'},
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
